### ISSUE TITLE
ImportError: No module named 'past'

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iatikit#50]
```
import iatikit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/iatikit/iatikit/__init__.py", line 4, in <module>
    from .data.registry import Registry
  File "/iatikit/iatikit/data/registry.py", line 6, in <module>
    from .publisher import PublisherSet
  File "/iatikit/iatikit/data/publisher.py", line 7, in <module>
    from past.builtins import basestring
ImportError: No module named 'past'
```

**Comment by andylolz** [comment]
This is supposedly fixed with `pip install future`, which is a requirement in setup.py. So marking this as fixed.
