### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'NoneType'

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iatikit#52]
### Describe the bug

Error appears when doing anything with recently downloaded data.

### To Reproduce

Steps to reproduce the behaviour:

```python
import iatikit

for x in iatikit.data().datasets:
    pass
```

…and see the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/iatikit/data/dataset.py", line 243, in __iter__
    paths = sorted(list(paths.values()))
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

### Additional context

Previously, failed XML downloads resulted in a blank file. Now, they result in a missing file. iatikit should probably cope with both.

**Comment by andylolz** [comment]
Fixed in 3e5080a29b9059cb66eeffdc5cf2d49082c6bb0b.
